namespace: lmw-fitness
GO_ENV: production
image:
  pullPolicy: Always
replicaCount: 1
storage:
  storageClass: nfs-csi
webserver:
  image:
    repository: lmwcode/image:tag
  port: 5052
  type: NodePort
  nodePort: 31313
  host: lmw-fitness.com
  path: /
  pathType: Prefix
api:
  image:
    repository: lmw.nexus.hyades.clusters.easlab.co.uk/backend-go-fitness-locator:7010db25f780795359f1d0c587142ae6e35089bd
  port: 8082
  type: NodePort
  nodePort: 30260
  host: api.lmw-fitness.com
  path: /api/
  pathType: ImplementationSpecific
database:
  name: gormproject
  user: postgres
  port: 5432
  servicePort: 5433
  type: ClusterIP
  sslMode: disable
livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
