apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-backend-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.api.host }}
      http:
        paths:
          - path: {{ .Values.api.path }}
            pathType: {{ .Values.api.pathType }}
            backend:
              service:
                name: {{ .Values.namespace }}-backend-service
                port:
                  number: {{ .Values.api.port }}