apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-service
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: backend-deployment-{{ .Values.namespace }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  volumeName: postgres-pv-{{ .Values.namespace }}
  storageClassName: {{ .Values.storage.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-{{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: backend-deployment-{{ .Values.namespace }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storage.storageClass }}
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" 