apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: frontend-ingress-{{ .Values.namespace }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.webserver.host }}
    http:
      paths:
      - path: {{ .Values.webserver.path }}
        pathType: {{ .Values.webserver.pathType }}
        backend:
          service:
            name: frontend-service
            port:
              number: {{ .Values.webserver.port }}